### ISSUE TITLE
[bug] Won't launch with mod installed

### ISSUE THREAD

**Issue by jaredniegas** [SCPSharp/scp-sharp#101]
### Version

1.10 / 1.19

### Current Behavior

The game doesn't launch when I have this mod installed.

[crash-2022-07-18_11.53.17-client.txt](https://github.com/SCPSharp/scp-sharp/files/9129360/crash-2022-07-18_11.53.17-client.txt)

**Comment by xtexChooser** [comment]
ops wait

**Comment by xtexChooser** [comment]
I am sorry for that, it is my bad.
[scp-sharp-1.10.1.jar.zip](https://github.com/SCPSharp/scp-sharp/files/9129971/scp-sharp-1.10.1.jar.zip)
Please try out this. If it works, I will publish a new patch version.
