### ISSUE TITLE
[BUG] Game Crashes on startup

### ISSUE THREAD

**Issue by theOneTrueFunniBoi** [SCPSharp/scp-sharp#194]
### Version

Fabric Loader / Minecraft 1.18.2, Mod Version 1.8 / 1.9

### Current Behavior

Game Crashes with Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'scpsharp'!

### Expected Behavior

Game Should Launch Fine

**Comment by theOneTrueFunniBoi** [comment]
EDIT: Game Crashes with Every 1.18.2 build of the mod. Version 1.6 - 1.9 are the ones with the specific error. The Other versions just crash with error code 1.

**Comment by xtexChooser** [comment]
any log?
please upload .minecraft/logs/latest.log and .minecraft/crash-report!

**Comment by xtexChooser** [comment]
ops, it is a fixed issue in #101 and #35.
I will create a 1.18.2 version with that patch.

**Comment by xtexChooser** [comment]
please try this: https://github.com/SCPSharp/scp-sharp/actions/runs/4452063826

**Comment by theOneTrueFunniBoi** [comment]
Bug is Fixed, no more Crashing (To my knowledge). Thanks for the patch!

**Comment by theOneTrueFunniBoi** [comment]
Nevermind keycard is broken
![image](https://user-images.githubusercontent.com/112577221/226078436-85a21755-aa12-47f0-bb6e-91aa0b8f9a40.png)

**Comment by xtexChooser** [comment]
yep, I haven't implement it yet(x
it is a far pending feature

**Comment by theOneTrueFunniBoi** [comment]
Ok, also quick question. Is SCP-Site 63 in this version or was that added in 1.19-1.9?

**Comment by xtexChooser** [comment]
Strictly speaking, this version contains a simplified version of Site-63 (63 is just a random number with no real documentation). But this version of the facility generator is a "feature" (and thus cannot be located), and has many problems and limitations when generating (large structures should not be a "feature"). So in 1.19 I refactored the whole facility generator framework to use "structure".

**Comment by theOneTrueFunniBoi** [comment]
So how do I find it?

**Comment by xtexChooser** [comment]
`/placefeature scpsharp:site63`. This command sometimes fails, after moving around try to spawn again.

**Comment by theOneTrueFunniBoi** [comment]
Thanks.
